.PHONY: build
build:
	GOOS=linux  GOARCH=amd64 go build -ldflags="-s -w" -o ./build/kommando.linux ./...
	GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ./build/kommando.macos ./...
	cp build/* ./example/
